# Generated by Django 5.1.6 on 2025-07-31 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
